services:
  backend:
    container_name: webportal-backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - backend/.env
    ports:
      - "30201:8000"
    networks:
      - dev_network

  frontend:
    container_name: webportal-frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - frontend/.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dev_network

networks:
  dev_network:
