services:
  splunk:
    container_name: splunk-enterprise
    image: splunk/splunk:latest
    restart: always
    environment:
      - "SPLUNK_START_ARGS=--accept-license"
      - "SPLUNK_PASSWORD=P@ssw0rd"
    volumes:
      - splunk-data:/opt/splunk
    ports:
      - "30800:8000"
      - "30888:8088"
      - "30889:8089"
      - "30997:9997"
      - "514:514/udp"
volumes:
  splunk-data:
