[unix_http_server]
file=/tmp/supervisor.sock
chmod=0755               

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB        
logfile_backups=10           
loglevel=info               
pidfile=/tmp/supervisord.pid 
nodaemon=true               
minfds=1024                  
minprocs=200

[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock 

[program:WebPortal_Frontend]
command=npm start
directory=/frontend
stdout_logfile=/frontend/log_out.log
stderr_logfile=/frontend/log_err.log
