[unix_http_server]
file=/tmp/supervisor.sock
chmod=0755

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord.pid
nodaemon=true
minfds=1024
minprocs=200

[inet_http_server]         ; inet (TCP) server disabled by default
port=127.0.0.1:9001        ; (ip_address:port specifier, *:port for all iface)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:Jboss_JBDOMAIN]
command=/opt/JBOSS/JBOSSMAIN/wildfly-10.0.0.Final/bin/domain.sh --host-config=host-master.xml -Djboss.domain.base.dir=/opt/JBOSS/JBDOMAIN/domain
directory=/opt/JBOSS/JBDOMAIN
stdout_logfile=/opt/JBOSS/JBDOMAIN/log_out.log
stderr_logfile=/opt/JBOSS/JBDOMAIN/log_err.log

[program:Jboss_Slave1]
command=/opt/JBOSS/JBOSSMAIN/wildfly-10.0.0.Final/bin/domain.sh --host-config=host-slave.xml -Djboss.domain.base.dir=/opt/JBOSS/Slave1/domain
directory=/opt/JBOSS/Slave1
stdout_logfile=/opt/JBOSS/Slave1/log_out.log
stderr_logfile=/opt/JBOSS/Slave1/log_err.log

[program:Jboss_Slave2]
command=/opt/JBOSS/JBOSSMAIN/wildfly-10.0.0.Final/bin/domain.sh --host-config=host-slave.xml -Djboss.domain.base.dir=/opt/JBOSS/Slave2/domain
directory=/opt/JBOSS/Slave2
stdout_logfile=/opt/JBOSS/Slave2/log_out.log
stderr_logfile=/opt/JBOSS/Slave2/log_err.log

[program:Splunk_IM]
command=systemctl restart splunk-otel-collector
