services:
  frontend:
    container_name: forescout-frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - frontend/.env
    ports:
      - "80:80"
      - "443:443"
      - "6082:443"
