---
- name: Installation Workspace.
  hosts: server
  connection: local
  gather_facts: false
  become: true
  vars:
    user: "user"
  environment:
    GNUTLS_CPUID_OVERRIDE: 0x1

  tasks:
    - include_tasks: ./docker-workspace/docker-install.yaml
    - include_tasks: ./docker-workspace/docker-compose-install.yaml
